- name: PING
  ansible.builtin.ping:

- name: Update package list
  apt:
    update_cache: yes

- name: Upgrade packages
  apt:
    upgrade: yes
    autoremove: yes 
    autoclean: yes  

- name: Install WireGuard package
  apt:
    name: wireguard
    state: present

- name: Check private_key_file for exists
  stat:
    path: "{{ WG_PATH }}/privatekey"
  register: private_key_file

- name: Generate keys for server
  shell: wg genkey | tee {{ WG_PATH }}/privatekey | wg pubkey | tee {{ WG_PATH }}/publickey
  when: private_key_file.stat.exists == false

- name: Change permissions for private key
  file:
    path: "{{ WG_PATH }}/privatekey"
    mode: '0600'

- name: env server private key
  shell: cat "{{ WG_PATH }}/privatekey"
  register: SERVER_PRIVATE_KEY_RAW

- name: INTERFACE_NAME_RAW
  shell: ip -o -4 route show to default | awk '{print $5}'
  register: INTERFACE_NAME_RAW

- name: Создание переменной FILE_CONTENT
  set_fact:
    SERVER_PRIVATE_KEY: "{{ SERVER_PRIVATE_KEY_RAW.stdout }}"

- name: Создание переменной INTERFACE_NAME_RAW
  set_fact:
    INTERFACE_NAME: "{{ INTERFACE_NAME_RAW.stdout }}"

- name: Generate test.conf from template
  template:
    src: "wg0.conf.j2"
    dest: "{{ WG_PATH_CONF }}"

- name: Добавление net.ipv4.ip_forward в sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    line: net.ipv4.ip_forward=1
  run_once: true

- name: Применение изменений в sysctl.conf
  shell: sysctl -p
  run_once: true

- name: Автоматизация команды systemctl enable
  systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started